spring:
  application:
    name: maestro-extensions
  autoconfigure:
    exclude:
  cloud:
    aws:
      credentials:
        access-key: foo
        secret-key: bar
      region:
        static: us-east-1
      endpoint: http://127.0.0.1:4566

server:
  port: 8081

extensions:
  maestro-base-url: http://localhost:8080/api/v3
  maestro-event-queue-url: http://localhost:4566/000000000000/maestro-event
  database:
    configs:
      jdbc-url: "jdbc:tc:postgresql:17:///maestro_local"
      jdbc-username: root
      db-type: postgres
      flyway-enabled: true
      workflow-database-error-retries: 3
      workflow-database-insert-batch-size: 32
      workflow-database-rewrite-batched-inserts: true
      workflow-database-login-timeout-seconds: 5
      workflow-database-socket-timeout-seconds: 50
      workflow-database-client-name: maestro-extensions-local
      workflow-database-connection-pool-size-max: 4
      workflow-database-connection-pool-idle-min: 4
      workflow-database-connection-lifetime-max: 50000
      workflow-database-connection-idle-timeout: 30000

logging:
  level:
    com:
      netflix: INFO
