/* Generated By:JJTree: Do not edit this line. ASTAllocationExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.netflix.sel.ast;

import com.netflix.sel.visitor.SelBaseNode;

public class ASTAllocationExpression extends SelBaseNode {
  public ASTAllocationExpression(int id) {
    super(id);
  }

  public ASTAllocationExpression(SelParser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. * */
  public Object jjtAccept(SelParserVisitor visitor, Object data) {

    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d06b210b3b5bd0bb1ce09bb4cf7741e7 (do not edit this line) */
