/* Generated By:JavaCC: Do not edit this line. SelParserTreeConstants.java Version 6.0_1 */
package com.netflix.sel.ast;

public interface SelParserTreeConstants {
  public int JJTEXECUTE = 0;
  public int JJTIMPORTDECLARATION = 1;
  public int JJTVARIABLEDECLARATOR = 2;
  public int JJTVARIABLEDECLARATORID = 3;
  public int JJTVOID = 4;
  public int JJTARRAYINITIALIZER = 5;
  public int JJTTYPE = 6;
  public int JJTPRIMITIVETYPE = 7;
  public int JJTCLASSTYPE = 8;
  public int JJTNAME = 9;
  public int JJTEXPRESSION = 10;
  public int JJTASSIGNMENT = 11;
  public int JJTASSIGNMENTOPERATOR = 12;
  public int JJTTERNARY = 13;
  public int JJTBINARYEXPR = 14;
  public int JJTUNARY = 15;
  public int JJTPRIMARYEXPRESSION = 16;
  public int JJTPRIMARYSUFFIX = 17;
  public int JJTARRAYIDX = 18;
  public int JJTMETHOD = 19;
  public int JJTPARAMS = 20;
  public int JJTLITERAL = 21;
  public int JJTALLOCATIONEXPRESSION = 22;
  public int JJTARGS = 23;
  public int JJTARRAYDIMS = 24;
  public int JJTSTATEMENT = 25;
  public int JJTBLOCK = 26;
  public int JJTLOCALVARIABLEDECLARATION = 27;
  public int JJTIFSTATEMENT = 28;
  public int JJTWHILESTATEMENT = 29;
  public int JJTFORSTATEMENT = 30;
  public int JJTFORINIT = 31;
  public int JJTFORUPDATE = 32;
  public int JJTBREAKSTATEMENT = 33;
  public int JJTCONTINUESTATEMENT = 34;
  public int JJTRETURNSTATEMENT = 35;
  public int JJTTHROWSTATEMENT = 36;

  public String[] jjtNodeName = {
    "Execute",
    "ImportDeclaration",
    "VariableDeclarator",
    "VariableDeclaratorId",
    "void",
    "ArrayInitializer",
    "Type",
    "PrimitiveType",
    "ClassType",
    "Name",
    "Expression",
    "Assignment",
    "AssignmentOperator",
    "Ternary",
    "BinaryExpr",
    "Unary",
    "PrimaryExpression",
    "PrimarySuffix",
    "ArrayIdx",
    "Method",
    "Params",
    "Literal",
    "AllocationExpression",
    "Args",
    "ArrayDims",
    "Statement",
    "Block",
    "LocalVariableDeclaration",
    "IfStatement",
    "WhileStatement",
    "ForStatement",
    "ForInit",
    "ForUpdate",
    "BreakStatement",
    "ContinueStatement",
    "ReturnStatement",
    "ThrowStatement",
  };
}
/* JavaCC - OriginalChecksum=8ae85cb361a77787afaa604a0f4850dd (do not edit this line) */
