spring:
  application:
    name: maestro
  autoconfigure:
    exclude:
  sleuth:
    sampler:
      # disable tracing
      probability: 0.0

server:
  port: 8080

maestro:
  notifier:
    type: sns
  publisher:
    type: sqs
  listener:
    type: sqs
  alerting:
    type: noop
  redis:
    enabled: false
  sel:
    thread-num: 3
    timeout-millis: 120000
    stack-limit: 128
    loop-limit: 25001
    array-limit: 25001
    length-limit: 10000
    visit-limit: 100000000
    memory-limit: 100000000
  cluster:
    name: test
  # step database related action config
  step-action:
    action-timeout: 5000
    check-interval: 500

engine:
  configs:
    # database config
    workflow-database-error-retries: 5
    workflow-database-insert-batch-size: 32
    workflow-database-rewrite-batched-inserts: true
    workflow-database-login-timeout-seconds: 5
    workflow-database-socket-timeout-seconds: 50
    jdbc-username: root
    jdbc-url: "jdbc:tc:cockroach:v22.2.19:///maestro_local"
    flyway-enabled: true
    workflow-database-client-name: maestro-local
    workflow-database-connection-pool-size-max: 8
    workflow-database-connection-pool-idle-min: 8
    workflow-database-connection-lifetime-max: 50000
    workflow-database-connection-idle-timeout: 30000
    # flow engine config
    flow-engine-address: http://${spring.cloud.client.ip-address}:${server.port}
    initial-maintenance-delay-millis: ${random.long[2000,5000]}
    internal-worker-num: 80

stepruntime:
  env: test
  foreach:
    loop-batch-limit: 50
    insert-batch-limit: 10
    run-job-batch-limit: 5
    get-rollup-batch-limit: 100
  subworkflow:
    always-pass-down-param-names: []
  cache:
    default-sha-cache-minutes: 43200  # 30 days
    default-sha-max-size: 100
    custom-sha-cache-minutes: 10
    custom-sha-max-size: 50
  # callback delay interval setting based on step instance status and step type.
  callback-delay-config:
    fixed-callback-delay-in-secs:
      RUNNING:
        default: 3
      WAITING_FOR_PERMITS:
        default: 5
      WAITING_FOR_SIGNALS:
        default: 5
      PAUSED:
        default: 5
      FINISHING:
        default: 5
      NOT_CREATED:
        default: 30

triggers:
  #time trigger configurations
  time-trigger:
    type: sqs
    trigger-batch-size: 10
    max-triggers-per-message: 200
  #signal trigger configurations
  signal-trigger:
    type: sqs

aws:
  sns:
    topic: arn:aws:sns:us-east-1:000000000000:maestro-test
    endpoint: http://localhost:4566
  sqs:
    start-workflow-job-queue-url: http://localhost:4566/000000000000/maestro-start-workflow-job
    run-workflow-instances-job-queue-url: http://localhost:4566/000000000000/maestro-run-workflow-instances-job.fifo
    terminate-instances-job-queue-url: http://localhost:4566/000000000000/maestro-terminate-instances-job
    terminate-then-run-instance-job-queue-url: http://localhost:4566/000000000000/maestro-terminate-then-run-instance-job
    publish-job-queue-url: http://localhost:4566/000000000000/maestro-publish-job-event
    delete-workflow-job-queue-url: http://localhost:4566/000000000000/maestro-delete-workflow-job
    step-wake-up-job-queue-url: http://localhost:4566/000000000000/maestro-step-wake-up-job.fifo
    time-trigger-execution-queue-url: http://localhost:4566/000000000000/maestro-time-trigger-execution
    signal-instance-queue-url: http://localhost:4566/000000000000/maestro-signal-instance.fifo
    signal-trigger-match-queue-url: http://localhost:4566/000000000000/maestro-signal-trigger-match.fifo
    signal-trigger-execution-queue-url: http://localhost:4566/000000000000/maestro-signal-trigger-execution.fifo

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_DEFAULT_REGION}
      auto: false
    stack:
      auto: false

logging:
  level:
    com:
      netflix: INFO
