name: 'codelimit'

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps: 
    - name: 'Checkout sources'
      uses: actions/checkout@v4

    - name: 'Run CodeLimit'
      uses: getcodelimit/codelimit-action@v1
